language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - python -m pip install -e ".[develop]"
script:
  - pytest
  - mypy .
notifications:
  email:
    on_success: always # default: change
    on_failure: always # default: always