name: Run tests
on: 
  push:
    branches:
      - master

jobs:
  build:
    name: Test and Type Check
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install
        run: |
          python -m pip install -e ".[develop]"
      - name: Type check
        run: |
          mypy . 
      - name: Tests
        run: |
          pytest
