name: Run tests
on: 
  push:
    branches:
      - master

jobs:
  build:
    name: Test and Type Check
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: Install
        run: |
          python -m pip install -e ".[develop]"
      - name: Type check
        run: |
          mypy . 
      - name: Tests
        run: |
          pytest
